### ISSUE TITLE
Type 5 message parsing

### ISSUE THREAD

**Issue by lanas1234** [bcl/aisparser#32]
Hi,

thanks for your work and effort in building this great decoder!

I'm start to working with it and I have no problem with normal message types (1,2,3,4) but I don't know how to work with type 5 sentences. Is it possible to do it with this parser? do you have any example?

I'm just interested in the name, mmsi and shiptype variables so if is not possible to decode type 5 messages is it possible to get these values somehow?

All the best

**Comment by bcl** [comment]
It shouldn't be any different than the other messages. Exactly what problem are you having?

**Comment by lanas1234** [comment]
Thanks for the answer!

I'm using the following code:
`/* -----------------------------------------------------------------------
   Process AIS messages read from stdin and output readable text fields
   Copyright 2006 by Brian C. Lane
   All Rights Reserved
   ----------------------------------------------------------------------- */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "portable.h"
#include "nmea.h"
#include "sixbit.h"
#include "vdm_parse.h"


int main( int argc, char *argv[] )
{
    ais_state     ais;
    char          buf[256];

    /* AIS message structures, only parse ones with positions */
  
    aismsg_5  msg_5;
    
	char   name[21]; 
    long   userid = 0;
    unsigned char  ship_type;

    /* Clear out the structures */
    memset( &ais, 0, sizeof( ais_state ) );

    /* Process incoming packets from stdin */
   
    if (argc<2) printf("\nTHERE'S NO INPUT!!");
    else{ 
		strcpy(buf, argv[1]);
        printf("UNO\n");
        if (assemble_vdm( &ais, buf ) == 0)
        {
			printf("DOS\n");
			/* Get the 6 bit message id */
            ais.msgid = (unsigned char) get_6bit( &ais.six_state, 6 );
            printf("Message type %u\n",ais.msgid);
            /* process message with appropriate parser */
            switch( ais.msgid ) {
                case 5:
                    if( parse_ais_5( &ais, &msg_5 ) == 0 )
                    {   
						printf("MENSAJE TIPO \n");				
                        userid = msg_5.userid;
                        strcpy(name,msg_5.name);
                        ship_type=msg_5.ship_type;
                    }
                    break;            
                                   
            }  /* switch msgid */
            
            printf( "%d\n", ais.msgid );//Message ID
            printf( "%ld\n", userid );//MMSI
            printf( "%s\n", name);//NAME
            printf( "%u",ship_type);//SHIP_TYPE
            
        }  /* if */

	}/* if argc */
    return 0;
}`

and typing in the command line one part or two part sentences I get:
`lousado:~/AISdecode/aisparser> ./ais_text ' '!' AIVDM,2,1,1,A,55?MbV02;H;s<HtKR20EHE:0@T4@Dn2222222216L961O5Gf0NSQEp6ClRp8,0*1C '
UNO
lousado:~/AISdecode/aisparser> ./ais_text ' '!' AIVDM,2,1,1,A,55?MbV02;H;s<HtKR20EHE:0@T4@Dn2222222216L961O5Gf0NSQEp6ClRp8,0*1C '!'AIVDM,2,2,1,A,88888888880,2*25'
UNO
`
which means that the code is stopping at `if (assemble_vdm( &ais, buf ) == 0)` any clu of what is happening?

All the best

**Comment by bcl** [comment]
The parser joins them, you feed incoming text into assemble_vdm and when it has a complete message it will return 0, you can then call parse_ais_5 on the ais structure to extract all the fields from it. The problem is you aren't looping on the input. See https://github.com/bcl/aisparser/blob/master/c/examples/text/main.c for an example of reading from stdin -- it doesn't include message 5 support though, you'll have to add a case statement for that.

**Comment by lanas1234** [comment]
Thanks for the answer!

My approach is a little different because I'm not interested in the 'Destination' field so I'm gonna 'cheat' my type 5 messages as they were a just one sentence (takinkg the first sentence and using a 'template' second sentence as I explain [here](https://stackoverflow.com/questions/56977022/is-really-important-the-second-part-sentence-in-a-type-5-ais-aivdm-message))
I'm also not interested in a continuous stdin loop because I want to use as a function/answer to a matlab script.
Anyway I think I've figured out, thanks for your indications
All the best
