### ISSUE TITLE
AIS TYPE 5 Error

### ISSUE THREAD

**Issue by rodrigobarrera1993** [bcl/aisparser#33]
Dear all,

I have been having troubles to parse AIS TYPE 5 messages (they come in 2 parts).

For the Following Messages:
!AIVDM,2,1,9,A,5:U8vcP2<qeM11QB220lE8<u=Dj0MD584pV22216Hh9;C1Pe0Jlm@D1H,0*74
!AIVDM,2,2,9,A,888888888888880,2*2D

!AIVDM,2,1,1,B,5:UF2F021k4I118F220ME9E0622222222222221@<PR<75Nn0B4m@D1H,0*53
!AIVDM,2,2,1,B,888888888888880,2*26
[AIVDM sample.docx](https://github.com/bcl/aisparser/files/4935012/AIVDM.sample.docx)

The first message comes as a type 5 message with error =1 which is expected. However, the second message comes with type 10 even though it is a type 5 continuation of the first one.

Anybody has experienced similar issue?

Best regards,

Rodrigo

EDIT: Apprently the asterisc symbol before the checksum is being changed when I update the comment.
I will attach a word file instead.

**Comment by bcl** [comment]
> EDIT: Apprently the asterisc symbol before the checksum is being changed when I update the comment.
> I will attach a word file instead.

You can post it as code by enclosing the block in triple-backtick-quotes:

```
!AIVDM,2,1,9,A,5:U8vcP2<qeM11QB220lE8<u=Dj0MD584pV22216Hh9;C1Pe0Jlm@D1H,0*74
!AIVDM,2,2,9,A,888888888888880,2*2D

!AIVDM,2,1,1,B,5:UF2F021k4I118F220ME9E0622222222222221@<PR<75Nn0B4m@D1H,0*53
!AIVDM,2,2,1,B,888888888888880,2*26
```
