### ISSUE TITLE
NMEA Data Parsing with ais_text.exe

### ISSUE THREAD

**Issue by mjswartz3141** [bcl/aisparser#6]
I can't figure out how I'm supposed to run the AIS text parser c example. I'm operating on Windows 10, but am running through cygwin. I built with `make ais_text`, which produced ais_text.exe and tried to run `ais_text.exe` with a text file containing NMEA input from https://en.wikipedia.org/wiki/NMEA_0183, but it just hangs. I also tried putting single lines from that text file in the command line, but I am hitting a dead end. The text file for reference contains

```
$GPGGA,092750.000,5321.6802,N,00630.3372,W,1,8,1.03,61.7,M,55.2,M,,*76
$GPGSA,A,3,10,07,05,02,29,04,08,13,,,,,1.72,1.03,1.38*0A
$GPGSV,3,1,11,10,63,137,17,07,61,098,15,05,59,290,20,08,54,157,30*70
$GPGSV,3,2,11,02,39,223,19,13,28,070,17,26,23,252,,04,14,186,14*79
$GPGSV,3,3,11,29,09,301,24,16,09,020,,36,,,*76
$GPRMC,092750.000,A,5321.6802,N,00630.3372,W,0.02,31.66,280511,,,A*43
$GPGGA,092751.000,5321.6802,N,00630.3371,W,1,8,1.03,61.7,M,55.3,M,,*75
$GPGSA,A,3,10,07,05,02,29,04,08,13,,,,,1.72,1.03,1.38*0A
$GPGSV,3,1,11,10,63,137,17,07,61,098,15,05,59,290,20,08,54,157,30*70
$GPGSV,3,2,11,02,39,223,16,13,28,070,17,26,23,252,,04,14,186,15*77
$GPGSV,3,3,11,29,09,301,24,16,09,020,,36,,,*76
$GPRMC,092751.000,A,5321.6802,N,00630.3371,W,0.06,31.66,280511,,,A*45
```

Any help would be great!

**Comment by bcl** [comment]
It expects the input to be on stdin, so `cat FILENAME.TXT | ais_text.exe` or `ais_text.exe < FILENAME.TXT` should work. The example you have doesn't contain any AIS sentences though, those are all from a GPS.
Take a look at the files in https://github.com/bcl/aisparser/tree/master/c/data for some examples.
